import Head from 'next/head'
import Header from '../components/Header'
import Categories from '../components/Categories'


export default function Home() {
  return (
    <div className='bg-[#FAF8ED]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='mx-auto w-9/12 '>
        <Header/>
        <Categories/>
      </div>
      
    </div>
  )
}
